spring.application.name=taskScheduler

spring.datasource.url=jdbc:postgresql://localhost:5432/taskSchedularDb
spring.datasource.username=deepak
spring.datasource.password=kumar

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=kumar
spring.rabbitmq.password=deepak
spring.rabbitmq.listener.simple.concurrency=5
spring.rabbitmq.listener.simple.max-concurrency=10
spring.rabbitmq.listener.simple.default-requeue-rejected=false

# --- Actuator / monitoring ---
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

server.port=8080